<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="projects" nsURI="http://www.eclipse.org/oomph/setup/projects/1.0"
    nsPrefix="projects">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="schemaLocation" value="http://git.eclipse.org/c/cdo/org.eclipse.oomph.git/plain/setups/models/Projects.ecore"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectsImportTask" eSuperTypes="../../org.eclipse.oomph.setup/model/Setup.ecore#//SetupTask">
    <eAnnotations source="http://www.eclipse.org/oomph/setup/Enablement">
      <details key="variableName" value="setup.projects.p2"/>
      <details key="repository" value="${releng.url}"/>
      <details key="installableUnits" value="org.eclipse.oomph.setup.projects.feature.group"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/oomph/setup/ValidTriggers">
      <details key="triggers" value="STARTUP MANUAL"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EReference" name="sourceLocators" lowerBound="1"
        upperBound="-1" eType="ecore:EClass ../../org.eclipse.oomph.resources/model/Resources.ecore#//SourceLocator"
        containment="true"/>
  </eClassifiers>
</ecore:EPackage>
