<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="@modelname@" nsURI="@NamespaceURI@" nsPrefix="@modelname@">
  <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
    <details key="schemaLocation" value="@SchemaLocation@"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="@TaskName@Task" eSuperTypes="../../org.eclipse.oomph.setup/model/Setup.ecore#//SetupTask">
    <eAnnotations source="http://www.eclipse.org/oomph/setup/Enablement">
      <details key="variableName" value="p2.@task.name@"/>
      <details key="repository" value="@EnablementURL@"/>
      <details key="installableUnits" value="@ProjectName@.feature.group"/>
    </eAnnotations>
    <eAnnotations source="http://www.eclipse.org/oomph/setup/ValidTriggers">
      <details key="triggers" value="@ValidTriggers@"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
