<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="setup" nsURI="http://www.eclipse.org/oomph/setup/1.0" nsPrefix="setup">
  <eAnnotations source="http://www.eclipse.org/oomph/base/LabelProvider">
    <details key="imageBaseURI" value="http://git.eclipse.org/c/oomph/org.eclipse.oomph.git/plain/plugins/org.eclipse.oomph.setup.edit/icons/full/obj16"/>
  </eAnnotations>
  <eClassifiers xsi:type="ecore:EClass" name="SetupTask" abstract="true" eSuperTypes="../../org.eclipse.oomph.base/model/Base.ecore#//ModelElement">
    <eOperations name="getScope" eType="#//Scope"/>
    <eOperations name="requires" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean">
      <eParameters name="setupTask" eType="#//SetupTask"/>
    </eOperations>
    <eOperations name="getValidTriggers" lowerBound="1" eType="#//TriggerSet"/>
    <eOperations name="getTriggers" lowerBound="1" eType="#//TriggerSet"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="iD" eType="ecore:EDataType ../../org.eclipse.oomph.base/model/Base.ecore#//ID"
        iD="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="id"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/oomph/setup/NoExpand"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType ../../org.eclipse.oomph.base/model/Base.ecore#//Text">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="scopeType" eType="#//ScopeType"
        changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="excludedTriggers" lowerBound="1"
        eType="#//TriggerSet" defaultValueLiteral=""/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="disabled" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="predecessors" upperBound="-1"
        eType="#//SetupTask">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="predecessor"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="successors" upperBound="-1"
        eType="#//SetupTask">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="successor"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="restrictions" upperBound="-1"
        eType="#//Scope">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="restriction"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="filter" eType="#//Filter">
      <eAnnotations source="http://www.eclipse.org/oomph/setup/NoExpand"/>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="SetupTaskContainer" abstract="true"
      eSuperTypes="../../org.eclipse.oomph.base/model/Base.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="setupTasks" upperBound="-1"
        eType="#//SetupTask" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="setupTask"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Scope" abstract="true" eSuperTypes="#//SetupTaskContainer">
    <eOperations name="getParentScope" eType="#//Scope"/>
    <eOperations name="getType" lowerBound="1" eType="#//ScopeType"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="description" eType="ecore:EDataType ../../org.eclipse.oomph.base/model/Base.ecore#//Text">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="qualifiedName" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" changeable="false"
        volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Index" eSuperTypes="../../org.eclipse.oomph.base/model/Base.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="discoverablePackages" upperBound="-1"
        eType="ecore:EClass http://www.eclipse.org/emf/2002/Ecore#//EPackage">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="discoverablePackage"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="productCatalogs" upperBound="-1"
        eType="#//ProductCatalog" containment="true" eOpposite="#//ProductCatalog/index"
        eKeys="#//Scope/name">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="productCatalog"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projectCatalogs" upperBound="-1"
        eType="#//ProjectCatalog" containment="true" eOpposite="#//ProjectCatalog/index"
        eKeys="#//Scope/name">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="projectCatalog"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CatalogSelection" eSuperTypes="../../org.eclipse.oomph.base/model/Base.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="productCatalogs" upperBound="-1"
        eType="#//ProductCatalog" eKeys="#//Scope/name">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="productCatalog"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projectCatalogs" upperBound="-1"
        eType="#//ProjectCatalog" eKeys="#//Scope/name">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="projectCatalog"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultProductVersions"
        upperBound="-1" eType="#//ProductToProductVersionMapEntry" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="defaultProductVersion"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="defaultStreams" upperBound="-1"
        eType="#//ProjectToStreamMapEntry" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="defaultStream"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="selectedStreams" upperBound="-1"
        eType="#//Stream" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductCatalog" eSuperTypes="#//Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//Index"
        transient="true" eOpposite="#//Index/productCatalogs"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="products" upperBound="-1"
        eType="#//Product" containment="true" eOpposite="#//Product/productCatalog"
        eKeys="#//Scope/name">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="product"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Product" eSuperTypes="#//Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="productCatalog" eType="#//ProductCatalog"
        transient="true" eOpposite="#//ProductCatalog/products" eKeys="#//Scope/name"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="versions" lowerBound="1"
        upperBound="-1" eType="#//ProductVersion" containment="true" eOpposite="#//ProductVersion/product"
        eKeys="#//Scope/name">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="version"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductVersion" eSuperTypes="#//Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="product" lowerBound="1"
        eType="#//Product" transient="true" eOpposite="#//Product/versions"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="requiredJavaVersion" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectContainer" abstract="true" interface="true"
      eSuperTypes="#//Scope">
    <eOperations name="getProjectContainer" eType="#//ProjectContainer"/>
    <eOperations name="getProjectCatalog" eType="#//ProjectCatalog"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projects" upperBound="-1"
        eType="#//Project" containment="true" eOpposite="#//Project/projectContainer"
        eKeys="#//Scope/name">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="project"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectCatalog" eSuperTypes="#//ProjectContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="index" eType="#//Index"
        transient="true" eOpposite="#//Index/projectCatalogs"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Project" eSuperTypes="#//ProjectContainer">
    <eStructuralFeatures xsi:type="ecore:EReference" name="streams" upperBound="-1"
        eType="#//Stream" containment="true" eOpposite="#//Stream/project" eKeys="#//Scope/name">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="stream"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projectContainer" eType="#//ProjectContainer"
        transient="true" eOpposite="#//ProjectContainer/projects"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="logicalProjectContainer"
        eType="#//ProjectContainer"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parentProject" eType="#//Project"
        changeable="false" volatile="true" transient="true" derived="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="projectCatalog" eType="#//ProjectCatalog"
        changeable="false" volatile="true" transient="true" derived="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Stream" eSuperTypes="#//Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="project" eType="#//Project"
        transient="true" eOpposite="#//Project/streams"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="User" eSuperTypes="#//Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="attributeRules" upperBound="-1"
        eType="#//AttributeRule" containment="true" eKeys="#//AttributeRule/attributeURI">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="attributeRule"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="acceptedLicenses" upperBound="-1"
        eType="#//LicenseInfo">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="acceptedLicense"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="unsignedPolicy" eType="#//UnsignedPolicy"
        defaultValueLiteral="PROMPT"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="questionnaireDate" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EDate"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="preferenceRecorderDefault"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean" defaultValueLiteral="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="AttributeRule" eSuperTypes="../../org.eclipse.oomph.base/model/Base.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="attributeURI" eType="ecore:EDataType ../../org.eclipse.oomph.base/model/Base.ecore#//URI"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LocationCatalog">
    <eStructuralFeatures xsi:type="ecore:EReference" name="installations" upperBound="-1"
        eType="#//InstallationToWorkspacesMapEntry" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="installation"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workspaces" upperBound="-1"
        eType="#//WorkspaceToInstallationsMapEntry" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="workspace"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Installation" eSuperTypes="#//Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="productVersion" lowerBound="1"
        eType="#//ProductVersion"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstallationTask" eSuperTypes="#//SetupTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="">
      <eAnnotations source="http://www.eclipse.org/oomph/setup/Variable">
        <eAnnotations source="Choice">
          <details key="value" value="${install.root/}${installation.id}"/>
          <details key="label" value="Installed in a uniquely-named folder within the root install folder"/>
        </eAnnotations>
        <eAnnotations source="Choice">
          <details key="value" value="${@id.location}"/>
          <details key="label" value="Installed in the specified absolute folder location"/>
        </eAnnotations>
        <details key="filter" value="canonical"/>
        <details key="type" value="STRING"/>
        <details key="label" value="Installation location rule"/>
        <details key="description" value="The rule for the absolute folder location where the product is installed"/>
        <details key="storageURI"/>
        <details key="explicitType" value="FOLDER"/>
        <details key="explicitLabel" value="Installation location"/>
        <details key="explicitDescription" value="The absolute folder location where the product is installed"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/oomph/setup/RuleVariable">
        <details key="name" value="install.root"/>
        <details key="type" value="FOLDER"/>
        <details key="label" value="Root install folder"/>
        <details key="defaultValue" value="${user.home}"/>
        <details key="description" value="The root install folder where all the products are installed"/>
        <details key="storageURI" value="scope://"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/oomph/setup/RuleVariable">
        <details key="name" value="installation.id"/>
        <details key="type" value="STRING"/>
        <details key="label" value="Installation folder name"/>
        <details key="defaultValue" value="${scope.product.name|installationID}"/>
        <details key="description" value="The name of the folder within the root install folder where the product is installed"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativeProductFolder"
        lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        defaultValueLiteral=""/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Workspace" eSuperTypes="#//Scope">
    <eStructuralFeatures xsi:type="ecore:EReference" name="streams" upperBound="-1"
        eType="#//Stream">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="stream"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkspaceTask" eSuperTypes="#//SetupTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString" defaultValueLiteral="">
      <eAnnotations source="http://www.eclipse.org/oomph/setup/Variable">
        <eAnnotations source="Choice">
          <details key="value" value="${installation.location/ws}"/>
          <details key="label" value="Located in a folder named 'ws' within the installation folder"/>
        </eAnnotations>
        <eAnnotations source="Choice">
          <details key="value" value="${workspace.container.root/}${workspace.id}"/>
          <details key="label" value="Located in a uniquely-named folder within the root workspace-container folder"/>
        </eAnnotations>
        <eAnnotations source="Choice">
          <details key="value" value="${@id.location}"/>
          <details key="label" value="Located in the specified absolute folder location"/>
        </eAnnotations>
        <details key="filter" value="canonical"/>
        <details key="type" value="STRING"/>
        <details key="label" value="Workspace location rule"/>
        <details key="description" value="The rule for the absolute folder location where the workspace is located"/>
        <details key="storageURI"/>
        <details key="explicitType" value="FOLDER"/>
        <details key="explicitLabel" value="Workspace location"/>
        <details key="explicitDescription" value="The absolute folder location where the workspace is located"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/oomph/setup/RuleVariable">
        <details key="name" value="workspace.container.root"/>
        <details key="type" value="FOLDER"/>
        <details key="label" value="Root workspace-container folder"/>
        <details key="defaultValue" value="${user.home}"/>
        <details key="description" value="The root workspace-container folder where all the workspaces are located"/>
        <details key="storageURI" value="scope://"/>
      </eAnnotations>
      <eAnnotations source="http://www.eclipse.org/oomph/setup/RuleVariable">
        <details key="name" value="workspace.id"/>
        <details key="type" value="STRING"/>
        <details key="label" value="Workspace folder name"/>
        <details key="defaultValue" value="${scope.project.name|workspaceID}"/>
        <details key="description" value="The name of the workspace folder within the root workspace-container folder where the workspaces are located"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Configuration" eSuperTypes="../../org.eclipse.oomph.base/model/Base.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EReference" name="installation" eType="#//Installation"
        containment="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="workspace" eType="#//Workspace"
        containment="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="CompoundTask" eSuperTypes="#//SetupTask #//SetupTaskContainer">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableTask" eSuperTypes="#//SetupTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="type" lowerBound="1" eType="#//VariableType"
        defaultValueLiteral="STRING"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/oomph/setup/NoExpand"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="defaultValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storePromptedValue" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        volatile="true" transient="true" defaultValueLiteral="true" derived="true">
      <eAnnotations source="http://www.eclipse.org/emf/2002/GenModel">
        <details key="suppressedSetVisibility" value="true"/>
        <details key="suppressedGetVisibility" value="true"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="storageURI" eType="ecore:EDataType ../../org.eclipse.oomph.base/model/Base.ecore#//URI"
        defaultValueLiteral="scope://"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="choices" upperBound="-1"
        eType="#//VariableChoice" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="choice"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="VariableChoice" eSuperTypes="../../org.eclipse.oomph.base/model/Base.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http://www.eclipse.org/oomph/setup/NoExpand"/>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="label" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="StringSubstitutionTask" eSuperTypes="#//SetupTask">
    <eAnnotations source="http://www.eclipse.org/oomph/setup/ValidTriggers">
      <details key="triggers" value="STARTUP MANUAL"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="RedirectionTask" eSuperTypes="#//SetupTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceURL" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetURL" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="EclipseIniTask" eSuperTypes="#//SetupTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="option" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="vm" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="LinkLocationTask" eSuperTypes="#//SetupTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="path" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreferenceTask" eSuperTypes="#//SetupTask">
    <eAnnotations source="http://www.eclipse.org/oomph/setup/ValidTriggers">
      <details key="triggers" value="STARTUP MANUAL"/>
    </eAnnotations>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="key" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceCopyTask" eSuperTypes="#//SetupTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="sourceURL" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetURL" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ResourceCreationTask" eSuperTypes="#//SetupTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="content" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="targetURL" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encoding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextModifyTask" eSuperTypes="#//SetupTask">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="uRL" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
        <details key="name" value="url"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="modifications" upperBound="-1"
        eType="#//TextModification" containment="true">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="modification"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="encoding" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="TextModification" eSuperTypes="../../org.eclipse.oomph.base/model/Base.ecore#//ModelElement">
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="pattern" lowerBound="1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="substitutions" upperBound="-1"
        eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="element"/>
        <details key="name" value="substitution"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProductToProductVersionMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//Product">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//ProductVersion">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
      </eAnnotations>
    </eStructuralFeatures>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="ProjectToStreamMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//Project">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" lowerBound="1" eType="#//Stream">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="kind" value="attribute"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="selection" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="InstallationToWorkspacesMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//Installation"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Workspace"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="WorkspaceToInstallationsMapEntry" instanceClassName="java.util.Map$Entry">
    <eStructuralFeatures xsi:type="ecore:EReference" name="key" lowerBound="1" eType="#//Workspace"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="value" upperBound="-1"
        eType="#//Installation"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="ScopeType">
    <eLiterals name="None"/>
    <eLiterals name="ProductCatalog" value="1"/>
    <eLiterals name="Product" value="2" literal="Eclipse"/>
    <eLiterals name="ProductVersion" value="3"/>
    <eLiterals name="ProjectCatalog" value="4"/>
    <eLiterals name="Project" value="5"/>
    <eLiterals name="Stream" value="6" literal="Stream"/>
    <eLiterals name="Installation" value="7"/>
    <eLiterals name="Workspace" value="8"/>
    <eLiterals name="User" value="9"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EEnum" name="Trigger">
    <eLiterals name="BOOTSTRAP"/>
    <eLiterals name="STARTUP" value="1"/>
    <eLiterals name="MANUAL" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="TriggerSet" instanceTypeName="java.util.Set&lt;org.eclipse.oomph.setup.Trigger>"/>
  <eClassifiers xsi:type="ecore:EEnum" name="VariableType">
    <eLiterals name="STRING"/>
    <eLiterals name="TEXT" value="1"/>
    <eLiterals name="PASSWORD" value="2"/>
    <eLiterals name="PATTERN" value="3"/>
    <eLiterals name="URI" value="4"/>
    <eLiterals name="FILE" value="5"/>
    <eLiterals name="FOLDER" value="6"/>
    <eLiterals name="RESOURCE" value="7"/>
    <eLiterals name="CONTAINER" value="8"/>
    <eLiterals name="PROJECT" value="9"/>
    <eLiterals name="BOOLEAN" value="10"/>
    <eLiterals name="INTEGER" value="11"/>
    <eLiterals name="FLOAT" value="12"/>
    <eLiterals name="JRE" value="13"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="LicenseInfo" instanceClassName="org.eclipse.oomph.setup.LicenseInfo"/>
  <eClassifiers xsi:type="ecore:EEnum" name="UnsignedPolicy">
    <eLiterals name="PROMPT"/>
    <eLiterals name="ACCEPT" value="1"/>
    <eLiterals name="DECLINE" value="2"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="Filter" instanceClassName="java.lang.String">
    <eAnnotations source="http://www.eclipse.org/emf/2002/Ecore">
      <details key="constraints" value="WellformedFilterExpression"/>
    </eAnnotations>
  </eClassifiers>
</ecore:EPackage>
