<?xml version="1.0" encoding="UTF-8"?>
<ecore:EPackage xmi:version="2.0" xmlns:xmi="http://www.omg.org/XMI" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
    xmlns:ecore="http://www.eclipse.org/emf/2002/Ecore" name="preferences" nsURI="http://www.eclipse.org/Oomph/preferences/1.0"
    nsPrefix="preferences">
  <eClassifiers xsi:type="ecore:EClass" name="PreferenceItem" abstract="true" eSuperTypes="../../org.eclipse.oomph.base/model/Base.ecore#//ModelElement">
    <eOperations name="getParent" eType="#//PreferenceNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="root" eType="#//PreferenceNode"
        changeable="false" volatile="true" transient="true" derived="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="scope" eType="#//PreferenceNode"
        changeable="false" volatile="true" transient="true" derived="true" resolveProxies="false"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="absolutePath" lowerBound="1"
        eType="#//URI" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="name" lowerBound="1" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="relativePath" lowerBound="1"
        eType="#//URI" changeable="false" volatile="true" transient="true" derived="true"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="ancestor" eType="#//PreferenceItem"
        changeable="false" volatile="true" derived="true" resolveProxies="false"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="PreferenceNode" eSuperTypes="#//PreferenceItem">
    <eOperations name="getNode" eType="#//PreferenceNode">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getNode" eType="#//PreferenceNode">
      <eParameters name="path" eType="#//URI"/>
    </eOperations>
    <eOperations name="getProperty" eType="#//Property">
      <eParameters name="name" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"/>
    </eOperations>
    <eOperations name="getProperty" eType="#//Property">
      <eParameters name="path" eType="#//URI"/>
    </eOperations>
    <eOperations name="getAncestor" eType="#//PreferenceNode"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//PreferenceNode"
        eOpposite="#//PreferenceNode/children"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="children" upperBound="-1"
        eType="#//PreferenceNode" containment="true" eOpposite="#//PreferenceNode/parent">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="child"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EReference" name="properties" upperBound="-1"
        eType="#//Property" containment="true" eOpposite="#//Property/parent" eKeys="#//PreferenceItem/name">
      <eAnnotations source="http:///org/eclipse/emf/ecore/util/ExtendedMetaData">
        <details key="name" value="property"/>
      </eAnnotations>
    </eStructuralFeatures>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="location" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EString"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EClass" name="Property" eSuperTypes="#//PreferenceItem">
    <eOperations name="getAncestor" eType="#//Property"/>
    <eStructuralFeatures xsi:type="ecore:EReference" name="parent" eType="#//PreferenceNode"
        eOpposite="#//PreferenceNode/properties"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="value" eType="#//EscapedString"/>
    <eStructuralFeatures xsi:type="ecore:EAttribute" name="nonDefault" eType="ecore:EDataType http://www.eclipse.org/emf/2002/Ecore#//EBoolean"
        changeable="false" volatile="true" transient="true" derived="true"/>
  </eClassifiers>
  <eClassifiers xsi:type="ecore:EDataType" name="EscapedString" instanceClassName="java.lang.String"/>
  <eClassifiers xsi:type="ecore:EDataType" name="URI" instanceClassName="org.eclipse.emf.common.util.URI"/>
</ecore:EPackage>
